name: Build and publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get full-upgrade
        sudo apt install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3

    - name: Preparing
      run: |
        mkdir openwrt
        cd openwrt
        wget https://downloads.openwrt.org/releases/22.03.6/targets/ramips/mt7620/openwrt-imagebuilder-22.03.6-ramips-mt7620.Linux-x86_64.tar.xz
        tar xf openwrt-imagebuilder-22.03.6-ramips-mt7620.Linux-x86_64.tar.xz

    - name: Make
      run: |
        cd openwrt/openwrt-imagebuilder-22.03.6-ramips-mt7620.Linux-x86_64
        make image PROFILE="tplink_archer-c20-v1" CONFIG_IPV6=n PACKAGES="uhttpd uhttpd-mod-ubus libiwinfo-lua luci-base luci-app-firewall luci-mod-admin-full luci-theme-bootstrap -ppp -ppp-mod-pppoe -ip6tables -odhcp6c -kmod-ipv6 -kmod-ip6tables -odhcpd-ipv6only -opkg"

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        path: /home/runner/work/owrt-archer-c20-v1/owrt-archer-c20-v1/openwrt/openwrt-imagebuilder-22.03.6-ramips-mt7620.Linux-x86_64/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/tmp/openwrt-22.03.6-ramips-mt7620-tplink_archer-c20-v1-squashfs-sysupgrade.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v4

    - name: Download builds
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: out

    - name: Create GitHub release
      id: github_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v22.03.6
        release_name: OpenWrt v22.03.6

    - name: Upload build to GitHub release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.github_release.outputs.upload_url }}
        asset_path: /home/runner/work/owrt-archer-c20-v1/owrt-archer-c20-v1/out/openwrt-22.03.6-ramips-mt7620-tplink_archer-c20-v1-squashfs-sysupgrade.bin
        asset_name: openwrt-22.03.6-ramips-mt7620-tplink_archer-c20-v1-squashfs-sysupgrade.bin
        asset_content_type: application/octet-stream
